[package]
name = "packx"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10.8"
rand = "0.8.5"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "packx"
harness = false
